<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function eventbrite_ui_menu() {
  $items['admin/settings/eventbrite/payment-settings'] = array(
    'title' => t('Payment Settings'),
    'description' => t('Configure default payment settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eventbrite_ui_default_payment_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'eventbrite_ui.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/settings/eventbrite/add-venue'] = array(
    'title' => 'Add Venue',
    'description' => 'Add an Eventbrite venue',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eventbrite_venue_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'eventbrite_ui.forms.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/settings/eventbrite/list-venues'] = array(
    'title' => 'List Venues',
    'description' => 'List Eventbrite venues',
    'page callback' => 'eventbrite_ui_venue_list',
//    'page arguments' => array('eventbrite_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'eventbrite_ui.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );
	/*
	
  $items['eventbrite_ui/events'] = array(
    'title' => t('Eventbrite Events'),
    'page callback' => 'eventbrite_ui_event_list',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'eventbrite_ui.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['eventbrite_ui/new-event'] = array(
    'title' => t('Create a new Event'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eventbrite_ui_event_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'eventbrite_ui.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['eventbrite_ui/event/%'] = array(
    'title' => 'Single Eventbrite Event',
    'page callback' => 'eventbrite_ui_event',
    'page arguments' => array(2),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'eventbrite_ui.pages.inc',
    'type' => MENU_CALLBACK,
  );
  
  $items['eventbrite_ui/event/%/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );
  
  $items['eventbrite_ui/event/%/edit'] = array(
    'title' => 'Edit Event',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eventbrite_ui_event_form', 2),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'eventbrite_ui.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );  
  */
  
  return $items;
}