<?php
// $Id$

// TODO: Add eventbrite_og_requirements (copy from Eventbrite Blocks)

// Selective groups states. chosen by the group admin
/*
define ('EVENTBRITE_OG_DISABLED', 'eb_og_disabled');
define ('EVENTBRITE_OG_SUBUSER', 'eb_og_subuser');
define ('EVENTBRITE_OG_CUSTOM', 'eb_og_custom');
*/
define ('EVENTBRITE_OG_DISABLED', 0);
define ('EVENTBRITE_OG_CUSTOM', 1);
define ('EVENTBRITE_OG_SUBUSER', 2);

/**
 * Implementation of hook_menu().
 */
function eventbrite_og_menu() {
  /* TODO: Paymnet settings by group not currently supported
  $items['eventbrite_og/payment-settings/%node'] = array(
    // TODO: Add group name to title field
    'title' => t('Eventbrite default payment settings for group'),
    'description' => t('Default payment settings for Eventbrite events created within this group'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eventbrite_og_default_payment_settings', 2),
    // TODO: Add group admin check for permissions
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'eventbrite_og.pages.inc',
  );
  */
  
  /* TODO: Venues by group not currently supported
  $items['eventbrite_og/venues/%node'] = array(
    // TODO: Add group name to title field
    'title' => t('Eventbrite venues for group'),
    'description' => t('Venues for Eventbrite events created within this group'),
    'page callback' => 'eventbrite_og_venue_list',
    'page arguments' => array(2),
    // TODO: Add group admin check for permissions
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'eventbrite_og.pages.inc',
  );
  
  $items['eventbrite_og/%node/venues/list'] = array(
    // TODO: Add group name to title field
    'title' => t('List Venues'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
    'file' => 'eventbrite_og.pages.inc',
  );
  
  $items['eventbrite_og/%node/venues/add'] = array(
    'title' => 'Add Venue',
    'description' => 'Add an Eventbrite venue',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eventbrite_venue_form'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eventbrite_user_default_payment_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'eventbrite_og.pages.inc',
  );
  */
  
  return $items;
}

/**
 * Implementation of the hook_permissions()
 */
function eventbrite_og_perm() {
  return array('administer eventbrite group accounts');
}


// TODO: This may not need to be in its own function after all, only call is in hook_nodeapi() load op
function _eventbrite_og_load($nid) {
  $result = db_query('SELECT * FROM {eventbrite_og} WHERE nid = %d', $nid);
  if ($row = db_fetch_object($result)) {
    return $row;
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function eventbrite_og_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  // If this node is a group type
  if (og_is_group_type($node->type)) {
    switch ($op) {
      case 'load':
        $result = db_query('SELECT * FROM {eventbrite_og} WHERE nid = %d', $node->nid);
        if ($row = db_fetch_object($result)) {
          $node->eventbrite_og_enabled = $row->eventbrite_og_enabled;
          $node->eventbrite_og_user_key = $row->eventbrite_og_user_key;
        }
        else {
          $node->eventbrite_og_enabled = 0;
          $node->eventbrite_og_user_key = '';
        }
        break;

      case 'prepare':
        break;

      case 'insert':
      case 'update':
        _eventbrite_og_group_submit($node);
        break;

      case 'delete':
        // TODO: delete group subuser when group is deleted?  Just here or on Eventbrite?
        /*
        $sql = "DELETE FROM {eventbrite_og} WHERE nid = %d";
        db_query($sql, $node->nid);
        */
        break;
    }
  }
}

/*
 * This is in a function so that it's easier to hack later
 */
function _eventbrite_og_options() {
  $options = array(
    EVENTBRITE_OG_DISABLED => t('Do not enable Eventbrite integration for this group type'),
    EVENTBRITE_OG_CUSTOM => t('Allow groups to enter an Eventbrite user key to manage their events'),
  );
  if (module_exists('eventbrite_subuser')) {
    $options[EVENTBRITE_OG_SUBUSER] = t('Allow groups to select from one of the primary site account\'s subusers');
  }
  return $options;
}

function eventbrite_og_form_node_type_form_alter(&$form, &$form_state) {
  $type = $form['#node_type']->type;
  if (og_is_group_type($type)) {
    // This is a group type so add form elements for eventbrite_og
    $form['og']['eventbrite_og'] = array(
      '#type' => 'radios',
      '#title' => t('Eventbrite integration for Organic Groups'),
      '#options' => _eventbrite_og_options(),
      '#default_value' => variable_get('eventbrite_og_'. $type, EVENTBRITE_OG_DISABLED),
      '#weight' => 10,
    );

    $form['#submit'][] = 'eventbrite_og_node_type_form_submit';
  }
}

function eventbrite_og_node_type_form_submit($form, &$form_state) {
  $form_values = $form_state['values'];
  variable_set('eventbrite_og_'. $form_values['type'], $form_values['eventbrite_og']);
}

function eventbrite_og_get_account_options($type) {
  $account_options = array();

  if ($allowed_options = variable_get('eventbrite_og_'. $type, array())) {
    $account_options[EVENTBRITE_OG_DISABLED] = t('Do not enable event management for this group');
    if (module_exists('eventbrite_subuser')) {
      if ($allowed_options[EVENTBRITE_OG_SUBUSER]) {
        $account_options[EVENTBRITE_OG_SUBUSER] = t('Create a subuser account under the site\' Eventbrite account');
      }
    }
    if ($allowed_options[EVENTBRITE_OG_CUSTOM]) {
      $account_options[EVENTBRITE_OG_CUSTOM] = t('Enter an Eventbrite user key to use as the Eventbrite account');
    }
    if ($allowed_options[EVENTBRITE_OG_INHERIT]) {
      $account_options[EVENTBRITE_OG_INHERIT] = t('Use the site Eventbrite user key');
    }
  }

  return $account_options;
}

function eventbrite_og_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node'])) {
    $node = $form['#node'];
    if ($form_id == $node->type .'_node_form' && og_is_group_type($node->type)) {
      $account_type = variable_get('eventbrite_og_'. $node->type, EVENTBRITE_OG_DISABLED);
      if ($account_type != EVENTBRITE_OG_DISABLED) {
        if (user_access('administer eventbrite group accounts')) {
          drupal_add_js(drupal_get_path('module', 'eventbrite_og')  .'/eventbrite_og.js', 'module');

          $form['eventbrite_og'] = array(
            '#type' => 'fieldset',
            '#title' => t('Eventbrite Settings'),
          );

          $form['eventbrite_og']['eventbrite_og_enabled'] = array(
            '#type' => 'radios',
            '#title' => t('Eventbrite Groups Integration'),
            '#options' => array(
              0 => t('Disabled'),
              1 => t('Enabled'),
            ),
            '#required' => 1,
            '#default_value' => $node->eventbrite_og_enabled,
            '#attributes' => array('class' => 'eventbrite_og-enabled'),
          );

          switch ($account_type) {
            case EVENTBRITE_OG_CUSTOM:
              $form['eventbrite_og']['eventbrite_og_user_key'] = array(
                '#type' => 'textfield',
                '#title' => t('User key'),
                // TODO: get link for user key
                '#description' => t('Please enter the user key to use for Eventbrite integration within this group.  You can find the user key at ...'),
                '#default_value' => $node->eventbrite_user_key,
                '#attributes' => array('class' => 'eventbrite_og-user-key'),
              );
              break;
            case EVENTBRITE_OG_SUBUSER:
              if (module_exists('eventbrite_subuser')) {
                $subuser_email_options = eventbrite_subuser_email_options();
                $form['eventbrite_og']['eventbrite_subuser_email'] = array(
                  '#type' => 'select',
                  '#title' => t('Subuser Account'),
                  '#options' => eventbrite_subuser_email_options(),
                  '#description' => t('Please select the subuser account to use for Eventbrite integration within this group.'),
                  '#default_value' => eventbrite_subuser_get_email($node->eventbrite_og_user_key),
                  '#attributes' => array('class' => 'eventbrite_og-user-key'),
                );
              }
              break;
          }          

          $form['#validate'][] = 'eventbrite_og_group_node_validate';
        }
      }
    }
  }
}

function eventbrite_og_group_node_validate($form, &$form_state) {
  $form_values = $form_state['values'];
  if ($form_values['eventbrite_og_enabled']) {
    $node = $form['#node'];
    $account_type = variable_get('eventbrite_og_'. $node->type, EVENTBRITE_OG_DISABLED);

    switch ($account_type) {
      case EVENTBRITE_OG_CUSTOM:
        if (empty($form_values['eventbrite_og_user_key'])) {
          form_set_error('eventbrite_og_user_key', t('You must enter a user key for the group account to enable Eventbrite integration.'));
        }
        if (!eventbrite_get('user_get_by_key', $form_values['eventbrite_og_user_key'])) {
          form_set_error('eventbrite_og_user_key', t('The Eventbrite API is not accepting that user key.'));
          return;
        }
        break;
      case EVENTBRITE_OG_SUBUSER:
        if (module_exists('eventbrite_subuser')) {
          if (empty($form_values['eventbrite_subuser_email'])) {
            form_set_error('eventbrite_subuser_email', t('You must select a subuser for the group account to enable Eventbrite integration.'));
          }
          if ($subuser = eventbrite_subuser_get($form_values['eventbrite_subuser_email'])) {
            if (!eventbrite_get('user_get_by_key', $subuser->user_key)) {
              form_set_error('eventbrite_subuser_email', t('The Eventbrite API is not authenticating that subuser.'));
              return;
            }
          }
          else {
            form_set_error('eventbrite_subuser_email', t('The email you entered does not match any subuser accounts.'));
          }
         }
        break;
    }
  }
}

function _eventbrite_og_group_submit($node) {
  $eventbrite_og = array(
    'nid' => $node->nid,
    'eventbrite_og_enabled' => $node->eventbrite_og_enabled,
    'eventbrite_og_user_key' => '',
  );

  if ($node->eventbrite_og_enabled) {
    $account_type = variable_get('eventbrite_og_'. $node->type, EVENTBRITE_OG_DISABLED);
    switch ($account_type) {
      case EVENTBRITE_OG_CUSTOM:
        $eventbrite_og['eventbrite_og_user_key'] = $node->eventbrite_og_user_key;
        break;
      case EVENTBRITE_OG_SUBUSER:
        if (module_exists('eventbrite_subuser')) {
          if ($subuser = eventbrite_subuser_get($node->eventbrite_subuser_email)) {
            $eventbrite_og['eventbrite_og_user_key'] = $subuser->user_key;
          }
          else {
            $eventbrite_og['eventbrite_og_enabled'] = 0;
          }
        }
        break;
    }
  }

  // Need to check if there is a row here already
  $result = db_query('SELECT * FROM {eventbrite_og} WHERE nid = %d', $node->nid);
  if ($db_row = db_fetch_object($result)) {
    drupal_write_record('eventbrite_og', $eventbrite_og, array('nid'));
  }
  else {
    drupal_write_record('eventbrite_og', $eventbrite_og);
  }
}

/**
* Implementation of hook_og_link_alter().
*/
function eventbrite_og_og_links_alter(&$links, $group_node) {
  // TODO: check if this is group admin
  if ($group_node->eventbrite_og_enabled) {
    // TODO: allow editing of venues by group
    //    $links['eventbrite_og_venues'] = l('Group venues', 'eventbrite_og/venues/'. $group_node->nid);
    // TODO: allow editing of payment settings by group
//    $links['eventbrite_og_payment_settings'] = l('Group payment settings', 'eventbrite_og/payment-settings/'. $group_node->nid);
  }
}
  
/**
 * Implementation of hook_field_access().
 *
 * IF there is a group context and IF Eventbrite has not been enabled for this group,
 *   then boot the field
 */
function eventbrite_og_field_access($op, $field, $account, $node = NULL) {
  if ($field['type'] == 'eventbrite_cck') {
    switch ($op) {
      case 'view':
      case 'edit':
        // Check if there is a group context
        if (og_is_group_post_type($node->type) && ($group_node = og_get_group_context($node->type))) {
          $account_type = variable_get('eventbrite_og_'. $group_node->type, EVENTBRITE_OG_DISABLED);
          if ($account_type == EVENTBRITE_OG_DISABLED) {
            // Do not show this field if the group type has not been Eventbrite enabled.
            return FALSE;
          }
          if (!$group_node->eventbrite_og_enabled) {
            // Do not show this field if the group node has not been Eventbrite enabled.
            return FALSE;
          }
        }
    }
  }
  return TRUE;
}

/**
 * Implementation of hook_eventbrite_request_alter(&$request).
 */
function eventbrite_og_eventbrite_request_alter(&$request) {
  // Check if there is a group context
  if ($group_node = og_get_group_context()) {
    // No need to check group type since field will be disabled when group node type not enabled

    // Check if eventbrite has been enabled for this group node -- this might already get checked
    if ($group_node->eventbrite_og_enabled) {
      switch ($request->op) {
        case 'user_list_events':
        case 'event_get':
        case 'event_new':
        case 'event_update':
        case 'ticket_new':
        case 'ticket_update':
        case 'user_list_venues':
          $request->module = 'eventbrite_og';
          $request->user_key = $group_node->eventbrite_og_user_key;
          break;
        default:
         // Don't make replacements if the $request->op didn't match the list
      }
    }
  }
}

