<?php
// $Id$
/**
* Declare information about a field type.
*
* @return
*   An array keyed by field type name. Each element of the array is an associative
*   array with these keys and values:
*   - "label": The human-readable label for the field type.
*/
function eventbrite_cck_field_info() {
  return array(
    'eventbrite_id' => array(
      'label' => t('Eventbrite Event'),
      'description' => t('Attach the event id to a node'),
      ),
    );
}

/**
 * Implementation of hook_content_is_empty().
 */
function eventbrite_cck_content_is_empty($item, $field) {
  if (empty($item['value']) && (string)$item['value'] !== '0') {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implementation of hook_field_formatter_info().
 */
function eventbrite_cck_field_formatter_info() {
  return array(
    'default' => array(
      'label' => t('Default'),
      'field types' => array('text'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
  );
}

function eventbrite_cck_widget_info() {
  return array(
    'eventbrite_id' => array(
      'label' => t('Eventbrite ID'),
      'field types' => array('eventbrite_id'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
  );
}
